const path=require('path');
module.exports={
    mode:'development',
    entry:{
        index:'./src/index.js',
        map:'./src/map.js'
    },
    output:{
        path:path.resolve(__dirname,'../dist'),
        filename:'[name].js'
    },
    module:{
        rules:[{
            test:/\.css$/,
            use:[{
                loader:'style-loader'
            },{
                loader:'css-loader'
            }]
        },{
            test:/\.(jpg|png)/,
            use:[{
                loader:'url-loader',
                options:{
                    limit:10000
                }
            }]
        },{
            test:/\.(js|jsx)/,
            use:[{
                loader:'babel-loader'
            }],
            exclude:/node_modules/
        },{
            test:/\.tsx?$/,
            use:[{
                loader:'ts-loader'
            }],
            exclude:/node_modules/
        }]
    },
    plugins:[
    ],
    devServer:{
        contentBase:path.resolve(__dirname,'../dist'),
        host:'localhost',
        compress:true,
        port:8090
    }
}